"""init

Revision ID: 0001
Revises:
Create Date: 2026-10-05 16:59:22.085533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    kelurahan = op.create_table(
        "kelurahan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kelurahan")),
        sa.UniqueConstraint("name", name=op.f("uq_kelurahan_name")),
    )
    # 16 kelurahan Kec. Semarang Barat, urutan & ejaan sama dengan design/ (daftar "Pilih kelurahan").
    op.bulk_insert(
        kelurahan,
        [
            {"id": i, "name": n}
            for i, n in enumerate(
                [
                    "Bojongsalaman",
                    "Bongsari",
                    "Cabean",
                    "Gisikdrono",
                    "Kalibanteng Kidul",
                    "Kalibanteng Kulon",
                    "Karangayu",
                    "Kembangarum",
                    "Krapyak",
                    "Krobokan",
                    "Manyaran",
                    "Ngemplak Simongan",
                    "Salamanmloyo",
                    "Tambakharjo",
                    "Tawangmas",
                    "Tawangsari",
                ],
                start=1,
            )
        ],
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "remaja",
                "pendamping",
                "konselor",
                "admin_kota",
                name="role",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_guardian",
                "active",
                "disabled",
                name="userstatus",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("kelurahan_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("auth_id", sa.String(length=64), nullable=True),
        sa.Column("pseudonym", sa.String(length=20), nullable=True),
        sa.Column("avatar", sa.SmallInteger(), nullable=True),
        sa.Column("birth_year", sa.SmallInteger(), nullable=True),
        sa.Column("assented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=False),
        sa.Column("failed_logins", sa.SmallInteger(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(role = 'remaja') = (auth_id IS NOT NULL)", name=op.f("ck_users_remaja_has_auth_id")
        ),
        sa.CheckConstraint(
            "role = 'remaja' OR (email IS NOT NULL AND password_hash IS NOT NULL)",
            name=op.f("ck_users_staff_has_login"),
        ),
        sa.CheckConstraint(
            "role IN ('remaja', 'pendamping', 'konselor', 'admin_kota')", name=op.f("ck_users_role")
        ),
        sa.CheckConstraint(
            "role NOT IN ('remaja', 'pendamping') OR kelurahan_id IS NOT NULL",
            name=op.f("ck_users_scoped_role_has_kelurahan"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_guardian', 'active', 'disabled')", name=op.f("ck_users_userstatus")
        ),
        sa.CheckConstraint("avatar BETWEEN 0 AND 7", name=op.f("ck_users_avatar_range")),
        sa.ForeignKeyConstraint(
            ["kelurahan_id"], ["kelurahan.id"], name=op.f("fk_users_kelurahan_id_kelurahan")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_id", name=op.f("uq_users_auth_id")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kelurahan_id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "hijau",
                "kuning",
                "oranye",
                "merah",
                name="risklevel",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "baru",
                "ditangani",
                "selesai",
                "dirujuk",
                name="casestatus",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("referred_to", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('hijau', 'kuning', 'oranye', 'merah')", name=op.f("ck_cases_risklevel")
        ),
        sa.CheckConstraint(
            "status IN ('baru', 'ditangani', 'selesai', 'dirujuk')",
            name=op.f("ck_cases_casestatus"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_cases_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["kelurahan_id"], ["kelurahan.id"], name=op.f("fk_cases_kelurahan_id_kelurahan")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cases_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index("ix_cases_kelurahan_status", "cases", ["kelurahan_id", "status"], unique=False)
    op.create_index(op.f("ix_cases_user_id"), "cases", ["user_id"], unique=False)
    op.create_table(
        "channel_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_channel_links_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_links")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_channel_links_telegram_id")),
        sa.UniqueConstraint("user_id", name=op.f("uq_channel_links_user_id")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "web",
                "telegram",
                name="channel",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('web', 'telegram')", name=op.f("ck_conversations_channel")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "guardian_consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email_enc", sa.LargeBinary(), nullable=False),
        sa.Column("guardian_name_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "relation",
            sa.Enum(
                "orang_tua",
                "wali",
                name="guardianrelation",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "declined",
                "revoked",
                name="consentstatus",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation IN ('orang_tua', 'wali')", name=op.f("ck_guardian_consents_guardianrelation")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'declined', 'revoked')",
            name=op.f("ck_guardian_consents_consentstatus"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_guardian_consents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardian_consents")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_guardian_consents_token_hash")),
    )
    op.create_index(
        op.f("ix_guardian_consents_user_id"), "guardian_consents", ["user_id"], unique=False
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column(
            "emotion",
            sa.Enum(
                "sedih",
                "cemas",
                "marah",
                "malu_bersalah",
                "senang",
                "netral",
                name="emotion",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("intensity", sa.SmallInteger(), nullable=False),
        sa.Column("note_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "emotion IN ('sedih', 'cemas', 'marah', 'malu_bersalah', 'senang', 'netral')",
            name=op.f("ck_journal_entries_emotion"),
        ),
        sa.CheckConstraint(
            "intensity BETWEEN 1 AND 5", name=op.f("ck_journal_entries_intensity_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_journal_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("user_id", "entry_date", name=op.f("uq_journal_entries_user_id")),
    )
    op.create_table(
        "screenings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "instrument",
            sa.Enum(
                "phq9",
                "gad7",
                name="instrument",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("instrument IN ('phq9', 'gad7')", name=op.f("ck_screenings_instrument")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_screenings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screenings")),
    )
    op.create_index(op.f("ix_screenings_user_id"), "screenings", ["user_id"], unique=False)
    op.create_table(
        "case_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("text_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_case_notes_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_notes_case_id_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_notes")),
    )
    op.create_index(op.f("ix_case_notes_case_id"), "case_notes", ["case_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sender",
            sa.Enum(
                "remaja",
                "bot",
                "pendamping",
                name="sender",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("encrypted_text", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sender IN ('remaja', 'bot', 'pendamping')", name=op.f("ck_messages_sender")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "emotion_scores",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_emotion_scores_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_emotion_scores")),
    )
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "hijau",
                "kuning",
                "oranye",
                "merah",
                name="risklevel",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("ter_score", sa.Float(), nullable=False),
        sa.Column("triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('hijau', 'kuning', 'oranye', 'merah')",
            name=op.f("ck_risk_assessments_risklevel"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_risk_assessments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_risk_assessments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
    )
    op.create_index(
        op.f("ix_risk_assessments_user_id"), "risk_assessments", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_assessments_user_id"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_table("emotion_scores")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_case_notes_case_id"), table_name="case_notes")
    op.drop_table("case_notes")
    op.drop_index(op.f("ix_screenings_user_id"), table_name="screenings")
    op.drop_table("screenings")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_guardian_consents_user_id"), table_name="guardian_consents")
    op.drop_table("guardian_consents")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("channel_links")
    op.drop_index(op.f("ix_cases_user_id"), table_name="cases")
    op.drop_index("ix_cases_kelurahan_status", table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("kelurahan")
    # ### end Alembic commands ###
