"""message kind order and case triggers

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 18:04:54.565876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "kind",
            sa.Enum(
                "text",
                "crisis_card",
                name="messagekind",
                native_enum=False,
                create_constraint=False,
                length=24,
            ),
            nullable=False,
            server_default="text",
        ),
    )
    op.create_check_constraint(
        op.f("ck_messages_messagekind"), "messages", "kind IN ('text', 'crisis_card')"
    )
    op.add_column(
        "messages", sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False)
    )
    op.create_unique_constraint(op.f("uq_messages_seq"), "messages", ["seq"])
    op.add_column("risk_assessments", sa.Column("case_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_risk_assessments_case_id"), "risk_assessments", ["case_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_risk_assessments_case_id_cases"),
        "risk_assessments",
        "cases",
        ["case_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_risk_assessments_case_id_cases"), "risk_assessments", type_="foreignkey"
    )
    op.drop_index(op.f("ix_risk_assessments_case_id"), table_name="risk_assessments")
    op.drop_column("risk_assessments", "case_id")
    op.drop_constraint(op.f("uq_messages_seq"), "messages", type_="unique")
    op.drop_column("messages", "seq")
    op.drop_column("messages", "kind")
    # ### end Alembic commands ###
