"""staff dashboard

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 00:45:27.528990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_follow_ups_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["users.id"],
            name=op.f("fk_follow_ups_staff_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_ups")),
    )
    op.create_index(op.f("ix_follow_ups_staff_id"), "follow_ups", ["staff_id"], unique=False)
    op.add_column("cases", sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("messages", sa.Column("author_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_messages_author_id_users"),
        "messages",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "users",
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "settings")
    op.drop_constraint(op.f("fk_messages_author_id_users"), "messages", type_="foreignkey")
    op.drop_column("messages", "author_id")
    op.drop_column("cases", "handled_at")
    op.drop_index(op.f("ix_follow_ups_staff_id"), table_name="follow_ups")
    op.drop_table("follow_ups")
    # ### end Alembic commands ###
